trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing Python...
    sudo apt-get install python3
    echo Running Python script...
    python3 main.py
  displayName: 'Run Python script'
